[package]
name = "bitcoin_quantity"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]

[dependencies]
bigdecimal = "0.1"
serde = { version = "1", optional = true }

[dev-dependencies]
serde_json = "1"
spectral = "0.6"
